import { Day } from "@/types/types";
 
export const events: Day[] = [
  {
    name: 'Tuesday',
    date: 'December 12',
    dateTime: '2023-12-12',
    performers: [
      {
        description: "John Mayer is a world-renowned guitarist and singer known for his emotional blues-rock performances.",
        name: 'John Mayer',
        type: 'Concert',
        time: '19:00',
        image: 'https://i.pinimg.com/474x/d3/5b/e4/d35be4bec547e5c27a43fba00a942215.jpg',
        location: 'Los Angeles',
        price: 30,
        status: 'Available',
      },
      {
        description: "David Guetta is a DJ and electronic music producer famous for his dance hits and energetic performances.",
        name: 'David Guetta',
        type: 'Workshop',
        time: '14:30',
        image: 'https://i.pinimg.com/474x/62/13/38/621338e2bc98b286c9cb74ef2e39b4bf.jpg',
        location: 'Los Angeles',
        price: 30,
        status: 'Available',
      },
      {
        description: "Taylor Swift is a pop sensation known for her chart-topping songs and captivating live concerts.",
        name: 'Taylor Swift',
        type: 'Concert',
        time: '20:15',
        image: 'https://i.pinimg.com/474x/d4/e1/b2/d4e1b2fd5da8f70bc716ddb98ffa9397.jpg',
        location: 'Chicago',
        price: 45,
        status: 'Available',
      },
      {
        description: "Ed Sheeran is a singer-songwriter famous for his heartfelt songs and acoustic performances.",
        name: 'Ed Sheeran',
        type: 'Concert',
        time: '21:30',
        image: 'https://i.pinimg.com/474x/f8/59/09/f859095b71a8cf5df2f9eca65faf31c4.jpg',
        location: 'San Francisco',
        price: 25,
        status: 'Sold Out',
      },
      {
        description: "Tim Cook is the CEO of Apple Inc. and a leading figure in the technology industry.",
        name: 'Tim Cook',
        type: 'Conference',
        time: '13:00',
        image: 'https://i.pinimg.com/474x/b8/94/89/b894894eb688a3f793201d71b4f6fd64.jpg',
        location: 'Miami',
        price: 55,
        status: 'Available',
      },
    ],
  },
  {
    name: 'Wednesday',
    date: 'December 13',
    dateTime: '2023-12-13',
    performers: [
      {
        description: "Elon Musk is an entrepreneur and tech visionary known for his innovations in the space and automotive industries.",
        name: 'Elon Musk',
        type: 'Conference',
        time: '16:00',
        image: 'https://i.pinimg.com/474x/62/1f/65/621f6520daaa29ad338da19b45ae3b7c.jpg',
        location: 'Los Angeles',
        price: 50,
        status: 'Available',
      },
      {
        description: "Sheryl Sandberg is a businesswoman and author, famous for her role as COO of Facebook and her advocacy for women's empowerment.",
        name: 'Sheryl Sandberg',
        type: 'Conference',
        time: '11:30',
        image: 'https://i.pinimg.com/474x/87/7b/00/877b00d934a3a2e84ddbc808d21a1b94.jpg',
        location: 'New York City',
        price: 60,
        status: 'Sold Out',
      },
      {
        description: "Armin van Buuren is a renowned DJ and music producer known for his contributions to the electronic dance music scene.",
        name: 'Armin van Buuren',
        type: 'Workshop',
        time: '15:00',
        image: 'https://i.pinimg.com/474x/f7/62/d4/f762d45bc79352dd2417a6dfd03f19fc.jpg',
        location: 'Chicago',
        price: 45,
        status: 'Available',
      },
      {
        description: "Satya Nadella is the CEO of Microsoft and a key figure in the technology and business world.",
        name: 'Satya Nadella',
        type: 'Conference',
        time: '14:30',
        image: 'https://i.pinimg.com/474x/04/4a/d1/044ad1c2782c79cafff70ec9ade95d20.jpg',
        location: 'Chicago',
        price: 45,
        status: 'Available',
      },
      {
        description: "Martin Garrix is a popular DJ and music producer known for his electronic dance hits and live performances.",
        name: 'Martin Garrix',
        type: 'Workshop',
        time: '13:30',
        image: 'https://i.pinimg.com/474x/e7/9b/da/e79bdafc7294180697e7d4b58d156104.jpg',
        location: 'Miami',
        price: 35,
        status: 'Available',
      },
    ],
  },
  {
    name: 'Thursday',
    date: 'December 14',
    dateTime: '2023-12-14',
    performers: [
      {
        description: "Bruno Mars is a pop sensation known for his energetic performances and chart-topping hits.",
        name: 'Bruno Mars',
        type: 'Concert',
        time: '21:45',
        image: 'https://i.pinimg.com/474x/c6/a1/68/c6a1686b7707aead89c5aa6ffbd41454.jpg',
        location: 'Miami',
        price: 35,
        status: 'Available',
      },
      {
        description: "Calvin Harris is a DJ and music producer famous for his electronic dance music tracks and DJ sets.",
        name: 'Calvin Harris',
        type: 'Workshop',
        time: '11:00',
        image: 'https://i.pinimg.com/474x/70/4c/f9/704cf9dbcd37f8aa799452947b9e8879.jpg',
        location: 'New York City',
        price: 40,
        status: 'Sold Out',
      },
      {
        description: "Barack Obama is a former U.S. President known for his leadership and contributions to politics and global affairs.",
        name: 'Barack Obama',
        type: 'Conference',
        time: '16:00',
        image: 'https://i.pinimg.com/474x/cf/f3/48/cff3482226e8409a8a54f0be9b365c2a.jpg',
        location: 'San Francisco',
        price: 55,
        status: 'Sold Out',
      },
      {
        description: "Andy Warhol is an iconic artist known for his groundbreaking contributions to the pop art movement.",
        name: 'Andy Warhol',
        type: 'Exhibition',
        time: '16:30',
        image: 'https://i.pinimg.com/474x/95/37/a5/9537a53de426f19954fc076fa934a2d0.jpg',
        location: 'San Francisco',
        price: 40,
        status: 'Sold Out',
      },
      {
        description: "Hardwell is a DJ and music producer celebrated for his electronic dance music tracks and live shows.",
        name: 'Hardwell',
        type: 'Workshop',
        time: '16:30',
        image: 'https://i.pinimg.com/474x/97/35/9a/97359ab44d83e0b4ff37e540d87621f3.jpg',
        location: 'San Francisco',
        price: 25,
        status: 'Sold Out',
      },
    ],
  },
  {
    name: 'Friday',
    date: 'December 15',
    dateTime: '2023-12-15',
    performers: [
      {
        description: "Pablo Picasso is a legendary artist known for his groundbreaking contributions to modern art.",
        name: 'Pablo Picasso',
        type: 'Exhibition',
        time: '10:30',
        image: 'https://i.pinimg.com/474x/98/1a/52/981a52f016e6526d00e04a428ec1469c.jpg',
        location: 'Paris',
        price: 20,
        status: 'Available',
      },
      {
        description: "Leonardo da Vinci is a Renaissance artist and inventor known for his iconic artworks and inventions.",
        name: 'Leonardo da Vinci',
        type: 'Exhibition',
        time: '12:00',
        image: 'https://i.pinimg.com/474x/8f/f3/4c/8ff34c7cc25f1425ec6b8d3c1ce673ed.jpg',
        location: 'London',
        price: 25,
        status: 'Sold Out',
      },
      {
        description: "Rihanna is a multi-talented artist known for her music, fashion, and cultural influence.",
        name: 'Rihanna',
        type: 'Performance',
        time: '21:00',
        image: 'https://i.pinimg.com/474x/ef/76/c3/ef76c346e6376cf058f6e3317069cb46.jpg',
        location: 'Miami',
        price: 65,
        status: 'Available',
      },
      {
        description: "Frida Kahlo is a celebrated artist known for her surreal and introspective artworks.",
        name: 'Frida Kahlo',
        type: 'Exhibition',
        time: '15:00',
        image: 'https://i.pinimg.com/474x/18/45/ad/1845add0f273c2f57233a0b3fb55b73f.jpg',
        location: 'Los Angeles',
        price: 35,
        status: 'Available',
      },
      {
        description: "Tim Cook is the CEO of Apple Inc. and a leading figure in the technology industry.",
        name: 'Tim Cook',
        type: 'Conference',
        time: '13:00',
        image: 'https://i.pinimg.com/474x/b8/94/89/b894894eb688a3f793201d71b4f6fd64.jpg',
        location: 'Miami',
        price: 55,
        status: 'Available',
      },
    ],
  },
  {
    name: 'Saturday',
    date: 'December 16',
    dateTime: '2023-12-16',
    performers: [
      {
        description: "Beyoncé is a global superstar known for her powerful performances and chart-topping music.",
        name: 'Beyoncé',
        type: 'Performance',
        time: '18:00',
        image: 'https://i.pinimg.com/474x/2a/b5/4f/2ab54f27287c1073edbc1fc16db78693.jpg',
        location: 'Los Angeles',
        price: 55,
        status: 'Available',
      },
      {
        description: "Lady Gaga is an iconic artist known for her avant-garde style and captivating live shows.",
        name: 'Lady Gaga',
        type: 'Performance',
        time: '19:30',
        image: 'https://i.pinimg.com/474x/10/77/b6/1077b6b8d8b90b4350e46209dbaf4c7a.jpg',
        location: 'New York City',
        price: 60,
        status: 'Sold Out',
      },
      {
        description: "Vincent van Gogh is a renowned artist known for his post-impressionist masterpieces.",
        name: 'Vincent van Gogh',
        type: 'Exhibition',
        time: '13:30',
        image: 'https://i.pinimg.com/474x/65/a1/9d/65a19d851442d5816097cadbae1c34fa.jpg',
        location: 'New York City',
        price: 30,
        status: 'Available',
      },
      {
        description: "Justin Timberlake is a multi-talented artist known for his music, acting, and dynamic live performances.",
        name: 'Justin Timberlake',
        type: 'Performance',
        time: '22:30',
        image: 'https://i.pinimg.com/474x/cb/f7/0d/cbf70de1e78293143a45329429d7ad84.jpg',
        location: 'Chicago',
        price: 70,
        status: 'Available',
      },
      {
        description: "Alicia Keys is a Grammy-winning artist known for her soulful music and powerful vocals.",
        name: 'Alicia Keys',
        type: 'Concert',
        time: '20:30',
        image: 'https://i.pinimg.com/474x/b3/7c/47/b37c47186efef28e3d6ffa0d323c7a8a.jpg',
        location: 'New York City',
        price: 40,
        status: 'Sold Out',
      },
      {
        description: "Adele is a globally acclaimed artist known for her emotional ballads and remarkable singing talent.",
        name: 'Adele',
        type: 'Performance',
        time: '21:00',
        image: 'https://i.pinimg.com/474x/bd/0f/73/bd0f737d959bf6e98f4879a31ad7d5ea.jpg',
        location: 'San Francisco',
        price: 75,
        status: 'Sold Out',
      },
    ] 
  },
]

//     {
//       name: 'Tuesday',
//       date: 'December 12',
//       dateTime: '2023-12-12',
//       performers: [
//         {
//           description: 'John Mayer',
//           name: 'John Mayer',
//           type: 'Concert',
//           time: '19:00',
//           image: 'https://i.pinimg.com/474x/d3/5b/e4/d35be4bec547e5c27a43fba00a942215.jpg',
//           location: 'Los Angeles',
//           price: 30,
//           status: 'Available',
//         },
//         {
//           description: 'David Guetta',
//           name: 'David Guetta',
//           type: 'Workshop',
//           time: '14:30',
//           image: 'https://i.pinimg.com/474x/62/13/38/621338e2bc98b286c9cb74ef2e39b4bf.jpg',
//           location: 'Los Angeles',
//           price: 30,
//           status: 'Available',
//         },
//         {
//           description: 'Taylor Swift',
//           name: 'Taylor Swift',
//           type: 'Concert',
//           time: '20:15',
//           image: 'https://i.pinimg.com/474x/d4/e1/b2/d4e1b2fd5da8f70bc716ddb98ffa9397.jpg',
//           location: 'Chicago',
//           price: 45,
//           status: 'Available',
//         },
//         {
//           description: 'Ed Sheeran',
//           name: 'Ed Sheeran',
//           type: 'Concert',
//           time: '21:30',
//           image: 'https://i.pinimg.com/474x/f8/59/09/f859095b71a8cf5df2f9eca65faf31c4.jpg',
//           location: 'San Francisco',
//           price: 25,
//           status: 'Sold Out',
//         },
//         {
//           description: 'Tim Cook',
//           name: 'Tim Cook',
//           type: 'Conference',
//           time: '13:00',
//           image: 'https://i.pinimg.com/474x/b8/94/89/b894894eb688a3f793201d71b4f6fd64.jpg',
//           location: 'Miami',
//           price: 55,
//           status: 'Available',
//         },
//       ],
//     },
//     {
//       name: 'Wednesday',
//       date: 'December 13',
//       dateTime: '2023-12-13',
//       performers: [
//         {
//           description: 'Elon Musk',
//           name: 'Elon Musk',
//           type: 'Conference',
//           time: '16:00',
//           image: 'https://i.pinimg.com/474x/62/1f/65/621f6520daaa29ad338da19b45ae3b7c.jpg',
//           location: 'Los Angeles',
//           price: 50,
//           status: 'Available',
//         },
//         {
//           description: 'Sheryl Sandberg',
//           name: 'Sheryl Sandberg',
//           type: 'Conference',
//           time: '11:30',
//           image: 'https://i.pinimg.com/474x/87/7b/00/877b00d934a3a2e84ddbc808d21a1b94.jpg',
//           location: 'New York City',
//           price: 60,
//           status: 'Sold Out',
//         },
//         {
//           description: 'Armin van Buuren',
//           name: 'Armin van Buuren',
//           type: 'Workshop',
//           time: '15:00',
//           image: 'https://i.pinimg.com/474x/f7/62/d4/f762d45bc79352dd2417a6dfd03f19fc.jpg',
//           location: 'Chicago',
//           price: 45,
//           status: 'Available',
//         },
//         {
//           description: 'Satya Nadella',
//           name: 'Satya Nadella',
//           type: 'Conference',
//           time: '14:30',
//           image: 'https://i.pinimg.com/474x/04/4a/d1/044ad1c2782c79cafff70ec9ade95d20.jpg',
//           location: 'Chicago',
//           price: 45,
//           status: 'Available',
//         },
//         {
//           description: 'Martin Garrix',
//           name: 'Martin Garrix',
//           type: 'Workshop',
//           time: '13:30',
//           image: 'https://i.pinimg.com/474x/e7/9b/da/e79bdafc7294180697e7d4b58d156104.jpg',
//           location: 'Miami',
//           price: 35,
//           status: 'Available',
//         },
//       ],
//     },
//     {
//       name: 'Thursday',
//       date: 'December 14',
//       dateTime: '2023-12-14',
//       performers: [
//         {
//           description: 'Bruno Mars',
//           name: 'Bruno Mars',
//           type: 'Concert',
//           time: '21:45',
//           image: 'https://i.pinimg.com/474x/c6/a1/68/c6a1686b7707aead89c5aa6ffbd41454.jpg',
//           location: 'Miami',
//           price: 35,
//           status: 'Available',
//         },
//         {
//           description: 'Calvin Harris',
//           name: 'Calvin Harris',
//           type: 'Workshop',
//           time: '11:00',
//           image: 'https://i.pinimg.com/474x/70/4c/f9/704cf9dbcd37f8aa799452947b9e8879.jpg',
//           location: 'New York City',
//           price: 40,
//           status: 'Sold Out',
//         },
//         {
//           description: 'Barack Obama',
//           name: 'Barack Obama',
//           type: 'Conference',
//           time: '16:00',
//           image: 'https://i.pinimg.com/474x/cf/f3/48/cff3482226e8409a8a54f0be9b365c2a.jpg',
//           location: 'San Francisco',
//           price: 55,
//           status: 'Sold Out',
//         },
//         {
//           description: 'Andy Warhol',
//           name: 'Andy Warhol',
//           type: 'Exhibition',
//           time: '16:30',
//           image: 'https://i.pinimg.com/474x/95/37/a5/9537a53de426f19954fc076fa934a2d0.jpg',
//           location: 'San Francisco',
//           price: 40,
//           status: 'Sold Out',
//         },
//         {
//           description: 'Hardwell',
//           name: 'Hardwell',
//           type: 'Workshop',
//           time: '16:30',
//           image: 'https://i.pinimg.com/474x/97/35/9a/97359ab44d83e0b4ff37e540d87621f3.jpg',
//           location: 'San Francisco',
//           price: 25,
//           status: 'Sold Out',
//         },
//       ],
  
//     },
//     {
//       name: 'Friday',
//       date: 'December 15',
//       dateTime: '2023-12-15',
//       performers: [
//         {
//           description: 'Pablo Picasso',
//           name: 'Pablo Picasso',
//           type: 'Exhibition',
//           time: '10:30',
//           image: 'https://i.pinimg.com/474x/98/1a/52/981a52f016e6526d00e04a428ec1469c.jpg',
//           location: 'Paris',
//           price: 20,
//           status: 'Available',
//         },
//         {
//           description: 'Leonardo da Vinci',
//           name: 'Leonardo da Vinci',
//           type: 'Exhibition',
//           time: '12:00',
//           image: 'https://i.pinimg.com/474x/8f/f3/4c/8ff34c7cc25f1425ec6b8d3c1ce673ed.jpg',
//           location: 'London',
//           price: 25,
//           status: 'Sold Out',
//         },
//         {
//           description: 'Rihanna',
//           name: 'Rihanna',
//           type: 'Performance',
//           time: '21:00',
//           image: 'https://i.pinimg.com/474x/ef/76/c3/ef76c346e6376cf058f6e3317069cb46.jpg',
//           location: 'Miami',
//           price: 65,
//           status: 'Available',
//         },
//         {
//           description: 'Frida Kahlo',
//           name: 'Frida Kahlo',
//           type: 'Exhibition',
//           time: '15:00',
//           image: 'https://i.pinimg.com/474x/18/45/ad/1845add0f273c2f57233a0b3fb55b73f.jpg',
//           location: 'Los Angeles',
//           price: 35,
//           status: 'Available',
//         },
//         {
//           description: 'Tim Cook',
//           name: 'Tim Cook',
//           type: 'Conference',
//           time: '13:00',
//           image: 'https://i.pinimg.com/474x/b8/94/89/b894894eb688a3f793201d71b4f6fd64.jpg',
//           location: 'Miami',
//           price: 55,
//           status: 'Available',
//         },
//       ],
//     },
//     {
//       name: 'Saturday',
//       date: 'December 16',
//       dateTime: '2023-12-16',
//       performers: [
//         {
//           description: 'Beyoncé',
//           name: 'Beyoncé',
//           type: 'Performance',
//           time: '18:00',
//           image: 'https://i.pinimg.com/474x/2a/b5/4f/2ab54f27287c1073edbc1fc16db78693.jpg',
//           location: 'Los Angeles',
//           price: 55,
//           status: 'Available',
//         },
//         {
//           description: 'Lady Gaga',
//           name: 'Lady Gaga',
//           type: 'Performance',
//           time: '19:30',
//           image: 'https://i.pinimg.com/474x/10/77/b6/1077b6b8d8b90b4350e46209dbaf4c7a.jpg',
//           location: 'New York City',
//           price: 60,
//           status: 'Sold Out',
//         },
//         {
//           description: 'Vincent van Gogh',
//           name: 'Vincent van Gogh',
//           type: 'Exhibition',
//           time: '13:30',
//           image: 'https://i.pinimg.com/474x/65/a1/9d/65a19d851442d5816097cadbae1c34fa.jpg',
//           location: 'New York City',
//           price: 30,
//           status: 'Available',
//         },
    
//         {
//           description: 'Justin Timberlake',
//           name: 'Justin Timberlake',
//           type: 'Performance',
//           time: '22:30',
//           image: 'https://i.pinimg.com/474x/cb/f7/0d/cbf70de1e78293143a45329429d7ad84.jpg',
//           location: 'Chicago',
//           price: 70,
//           status: 'Available',
//         },
//         {
//           description: 'Alicia Keys',
//           name: 'Alicia Keys',
//           type: 'Concert',
//           time: '20:30',
//           image: 'https://i.pinimg.com/474x/b3/7c/47/b37c47186efef28e3d6ffa0d323c7a8a.jpg',
//           location: 'New York City',
//           price: 40,
//           status: 'Sold Out',
//         },
//         {
//           description: 'Adele',
//           name: 'Adele',
//           type: 'Performance',
//           time: '21:00',
//           image: 'https://i.pinimg.com/474x/bd/0f/73/bd0f737d959bf6e98f4879a31ad7d5ea.jpg',
//           location: 'San Francisco',
//           price: 75,
//           status: 'Sold Out',
//         },
//       ],
//     },
// ];